Feature/cal and control
jasperweyne/helpless-kiwi pull request #271
Opened 2022-03-28 23:29 UTC by A-Daneel

C&C pull request. calendar and commands.
did the tests as well. as far as what made sense.

I've noticed we return a lot of [datatype] | null, maybe we should rethink that...

2022-03-30 22:24 UTC, jasperweyne requested changes
A number of small comments. Please also take [this comment](https://github.com/jasperweyne/helpless-kiwi/pull/270/files#r838976231) on #270  into consideration, as those are also applicable here.

2022-03-30 22:24 UTC, jasperweyne commented on tests/Unit/Calendar/ICalProviderTest.php
> +    /** @var activity */
Please replace this with `Activity` as this will improve typehints

2022-04-12 15:36 UTC, jasperweyne requested changes
A small casings issue, but overall looks good

2022-04-13 18:27 UTC, A-Daneel commented on tests/Unit/Calendar/ICalProviderTest.php
> +    /** @var activity */
should be resolved now. first try success on the third attempt!

2022-05-02 12:58 UTC, jasperweyne approved these changes

2022-05-02 12:58 UTC, merged